name: Update LG Flyer

on:
  schedule:
    # Runs every Thursday at 9 PM EST / 1 AM UTC (Friday)
    - cron: '0 2 * * FRI'
  workflow_dispatch:

jobs:
  update-flyer:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

    # Pass the secrets to the Python script
    - name: Run Python script to download the flyer
      run: |
        python scripts/update_lg_flyer.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}

    - name: Commit and push changes
      run: |
        git config --local user.email "biojameskim2002@gmail.com"
        git config --local user.name "James Kim"
        git add src/assets/large_group/lg_graphics/lg_flyer.png
        git commit -m "Update LG flyer"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
